// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clicksByHourOfDay = `-- name: ClicksByHourOfDay :many
SELECT
    extract(hour FROM bucket)::integer AS hour,
    sum(clicks)::bigint AS clicks
FROM click_hourly
WHERE workspace_id = $1
  AND bucket >= $2
  AND bucket < $3
GROUP BY hour
ORDER BY hour
`

type ClicksByHourOfDayParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
}

type ClicksByHourOfDayRow struct {
	Hour   int32
	Clicks int64
}

func (q *Queries) ClicksByHourOfDay(ctx context.Context, arg ClicksByHourOfDayParams) ([]ClicksByHourOfDayRow, error) {
	rows, err := q.db.Query(ctx, clicksByHourOfDay, arg.WorkspaceID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClicksByHourOfDayRow{}
	for rows.Next() {
		var i ClicksByHourOfDayRow
		if err := rows.Scan(&i.Hour, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clicksByWeekday = `-- name: ClicksByWeekday :many
SELECT
    extract(isodow FROM bucket)::integer AS weekday,
    sum(clicks)::bigint AS clicks
FROM click_hourly
WHERE workspace_id = $1
  AND bucket >= $2
  AND bucket < $3
GROUP BY weekday
ORDER BY weekday
`

type ClicksByWeekdayParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
}

type ClicksByWeekdayRow struct {
	Weekday int32
	Clicks  int64
}

func (q *Queries) ClicksByWeekday(ctx context.Context, arg ClicksByWeekdayParams) ([]ClicksByWeekdayRow, error) {
	rows, err := q.db.Query(ctx, clicksByWeekday, arg.WorkspaceID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClicksByWeekdayRow{}
	for rows.Next() {
		var i ClicksByWeekdayRow
		if err := rows.Scan(&i.Weekday, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clicksInRange = `-- name: ClicksInRange :one
SELECT coalesce(sum(clicks), 0)::bigint
FROM click_hourly
WHERE workspace_id = $1
  AND bucket >= $2
  AND bucket < $3
`

type ClicksInRangeParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
}

func (q *Queries) ClicksInRange(ctx context.Context, arg ClicksInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, clicksInRange, arg.WorkspaceID, arg.FromTime, arg.ToTime)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const clicksOverTime = `-- name: ClicksOverTime :many
SELECT
    date_trunc($1::text, bucket)::timestamptz AS period,
    sum(clicks)::bigint AS clicks
FROM click_hourly
WHERE workspace_id = $2
  AND bucket >= $3
  AND bucket < $4
GROUP BY period
ORDER BY period ASC
`

type ClicksOverTimeParams struct {
	Granularity string
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
}

type ClicksOverTimeRow struct {
	Period time.Time
	Clicks int64
}

func (q *Queries) ClicksOverTime(ctx context.Context, arg ClicksOverTimeParams) ([]ClicksOverTimeRow, error) {
	rows, err := q.db.Query(ctx, clicksOverTime,
		arg.Granularity,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClicksOverTimeRow{}
	for rows.Next() {
		var i ClicksOverTimeRow
		if err := rows.Scan(&i.Period, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clicksOverTimeForLink = `-- name: ClicksOverTimeForLink :many
SELECT
    date_trunc($1::text, bucket)::timestamptz AS period,
    sum(clicks)::bigint AS clicks
FROM click_hourly
WHERE link_id = $2
  AND bucket >= $3
  AND bucket < $4
GROUP BY period
ORDER BY period ASC
`

type ClicksOverTimeForLinkParams struct {
	Granularity string
	LinkID      uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
}

type ClicksOverTimeForLinkRow struct {
	Period time.Time
	Clicks int64
}

func (q *Queries) ClicksOverTimeForLink(ctx context.Context, arg ClicksOverTimeForLinkParams) ([]ClicksOverTimeForLinkRow, error) {
	rows, err := q.db.Query(ctx, clicksOverTimeForLink,
		arg.Granularity,
		arg.LinkID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClicksOverTimeForLinkRow{}
	for rows.Next() {
		var i ClicksOverTimeForLinkRow
		if err := rows.Scan(&i.Period, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDomainIssues = `-- name: CountDomainIssues :one
SELECT count(*) FROM domains WHERE workspace_id = $1 AND status <> 'active'
`

func (q *Queries) CountDomainIssues(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDomainIssues, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpiringAPIKeys = `-- name: CountExpiringAPIKeys :one
SELECT count(*) FROM api_keys
WHERE workspace_id = $1 AND revoked_at IS NULL
  AND expires_at > now() AND expires_at <= now() + interval '7 days'
`

func (q *Queries) CountExpiringAPIKeys(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiringAPIKeys, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpiringLinks = `-- name: CountExpiringLinks :one
SELECT count(*) FROM links
WHERE workspace_id = $1 AND status = 'active'
  AND expires_at > now() AND expires_at <= now() + interval '7 days'
`

func (q *Queries) CountExpiringLinks(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiringLinks, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteClickEventsBefore = `-- name: DeleteClickEventsBefore :execrows
DELETE FROM click_events WHERE clicked_at < $1
`

// Retention: raw events age out, rollups are kept indefinitely because they
// are tiny. Called by the worker's periodic maintenance pass.
func (q *Queries) DeleteClickEventsBefore(ctx context.Context, clickedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClickEventsBefore, clickedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVisitorDimensionsBefore = `-- name: DeleteVisitorDimensionsBefore :execrows
DELETE FROM click_dimension_daily
WHERE dimension = 'visitor' AND day < $1
`

// Visitor hashes have the same retention window as raw click events. Other
// aggregate dimensions remain tiny and are retained indefinitely.
func (q *Queries) DeleteVisitorDimensionsBefore(ctx context.Context, day time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVisitorDimensionsBefore, day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const filteredClicksByHourOfDay = `-- name: FilteredClicksByHourOfDay :many
SELECT extract(hour FROM click_hourly.bucket)::integer AS hour, sum(click_hourly.clicks)::bigint AS clicks
FROM click_hourly
JOIN links ON links.id = click_hourly.link_id
WHERE click_hourly.workspace_id = $1
  AND click_hourly.bucket >= $2 AND click_hourly.bucket < $3
  AND ($4::uuid IS NULL OR links.domain_id = $4)
  AND ($5::uuid IS NULL OR links.id = $5)
GROUP BY hour ORDER BY hour
`

type FilteredClicksByHourOfDayParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
	DomainID    *uuid.UUID
	LinkID      *uuid.UUID
}

type FilteredClicksByHourOfDayRow struct {
	Hour   int32
	Clicks int64
}

func (q *Queries) FilteredClicksByHourOfDay(ctx context.Context, arg FilteredClicksByHourOfDayParams) ([]FilteredClicksByHourOfDayRow, error) {
	rows, err := q.db.Query(ctx, filteredClicksByHourOfDay,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
		arg.DomainID,
		arg.LinkID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilteredClicksByHourOfDayRow{}
	for rows.Next() {
		var i FilteredClicksByHourOfDayRow
		if err := rows.Scan(&i.Hour, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredClicksByWeekday = `-- name: FilteredClicksByWeekday :many
SELECT extract(isodow FROM click_hourly.bucket)::integer AS weekday, sum(click_hourly.clicks)::bigint AS clicks
FROM click_hourly
JOIN links ON links.id = click_hourly.link_id
WHERE click_hourly.workspace_id = $1
  AND click_hourly.bucket >= $2 AND click_hourly.bucket < $3
  AND ($4::uuid IS NULL OR links.domain_id = $4)
  AND ($5::uuid IS NULL OR links.id = $5)
GROUP BY weekday ORDER BY weekday
`

type FilteredClicksByWeekdayParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
	DomainID    *uuid.UUID
	LinkID      *uuid.UUID
}

type FilteredClicksByWeekdayRow struct {
	Weekday int32
	Clicks  int64
}

func (q *Queries) FilteredClicksByWeekday(ctx context.Context, arg FilteredClicksByWeekdayParams) ([]FilteredClicksByWeekdayRow, error) {
	rows, err := q.db.Query(ctx, filteredClicksByWeekday,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
		arg.DomainID,
		arg.LinkID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilteredClicksByWeekdayRow{}
	for rows.Next() {
		var i FilteredClicksByWeekdayRow
		if err := rows.Scan(&i.Weekday, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredClicksInRange = `-- name: FilteredClicksInRange :one
SELECT coalesce(sum(click_hourly.clicks), 0)::bigint
FROM click_hourly
JOIN links ON links.id = click_hourly.link_id
WHERE click_hourly.workspace_id = $1
  AND click_hourly.bucket >= $2
  AND click_hourly.bucket < $3
  AND ($4::uuid IS NULL OR links.domain_id = $4)
  AND ($5::uuid IS NULL OR links.id = $5)
`

type FilteredClicksInRangeParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
	DomainID    *uuid.UUID
	LinkID      *uuid.UUID
}

func (q *Queries) FilteredClicksInRange(ctx context.Context, arg FilteredClicksInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, filteredClicksInRange,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
		arg.DomainID,
		arg.LinkID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const filteredClicksOverTime = `-- name: FilteredClicksOverTime :many
SELECT
    date_trunc($1::text, click_hourly.bucket)::timestamptz AS period,
    sum(click_hourly.clicks)::bigint AS clicks
FROM click_hourly
JOIN links ON links.id = click_hourly.link_id
WHERE click_hourly.workspace_id = $2
  AND click_hourly.bucket >= $3
  AND click_hourly.bucket < $4
  AND ($5::uuid IS NULL OR links.domain_id = $5)
  AND ($6::uuid IS NULL OR links.id = $6)
GROUP BY period
ORDER BY period ASC
`

type FilteredClicksOverTimeParams struct {
	Granularity string
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
	DomainID    *uuid.UUID
	LinkID      *uuid.UUID
}

type FilteredClicksOverTimeRow struct {
	Period time.Time
	Clicks int64
}

func (q *Queries) FilteredClicksOverTime(ctx context.Context, arg FilteredClicksOverTimeParams) ([]FilteredClicksOverTimeRow, error) {
	rows, err := q.db.Query(ctx, filteredClicksOverTime,
		arg.Granularity,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
		arg.DomainID,
		arg.LinkID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilteredClicksOverTimeRow{}
	for rows.Next() {
		var i FilteredClicksOverTimeRow
		if err := rows.Scan(&i.Period, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredTopLinks = `-- name: FilteredTopLinks :many
SELECT links.id, links.slug, links.title, links.destination_url, domains.hostname,
       sum(click_hourly.clicks)::bigint AS clicks
FROM click_hourly
JOIN links ON links.id = click_hourly.link_id
JOIN domains ON domains.id = links.domain_id
WHERE click_hourly.workspace_id = $1
  AND click_hourly.bucket >= $2 AND click_hourly.bucket < $3
  AND ($4::uuid IS NULL OR links.domain_id = $4)
  AND ($5::uuid IS NULL OR links.id = $5)
GROUP BY links.id, links.slug, links.title, links.destination_url, domains.hostname
ORDER BY clicks DESC LIMIT $6
`

type FilteredTopLinksParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
	DomainID    *uuid.UUID
	LinkID      *uuid.UUID
	RowLimit    int32
}

type FilteredTopLinksRow struct {
	ID             uuid.UUID
	Slug           string
	Title          *string
	DestinationUrl string
	Hostname       string
	Clicks         int64
}

func (q *Queries) FilteredTopLinks(ctx context.Context, arg FilteredTopLinksParams) ([]FilteredTopLinksRow, error) {
	rows, err := q.db.Query(ctx, filteredTopLinks,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
		arg.DomainID,
		arg.LinkID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilteredTopLinksRow{}
	for rows.Next() {
		var i FilteredTopLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.DestinationUrl,
			&i.Hostname,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkClickTotals = `-- name: LinkClickTotals :one
SELECT
    coalesce(sum(clicks), 0)::bigint AS total_clicks,
    coalesce(sum(clicks) FILTER (WHERE bucket >= date_trunc('day', now())), 0)::bigint AS clicks_today
FROM click_hourly
WHERE link_id = $1
`

type LinkClickTotalsRow struct {
	TotalClicks int64
	ClicksToday int64
}

func (q *Queries) LinkClickTotals(ctx context.Context, linkID uuid.UUID) (LinkClickTotalsRow, error) {
	row := q.db.QueryRow(ctx, linkClickTotals, linkID)
	var i LinkClickTotalsRow
	err := row.Scan(&i.TotalClicks, &i.ClicksToday)
	return i, err
}

const recentClickEvents = `-- name: RecentClickEvents :many
SELECT id, link_id, workspace_id, clicked_at, ip_hash, country, city, device, os, browser, referrer_host, referrer, utm_source, utm_medium, utm_campaign FROM click_events
WHERE link_id = $1
ORDER BY clicked_at DESC
LIMIT $2
`

type RecentClickEventsParams struct {
	LinkID uuid.UUID
	Limit  int32
}

func (q *Queries) RecentClickEvents(ctx context.Context, arg RecentClickEventsParams) ([]ClickEvent, error) {
	rows, err := q.db.Query(ctx, recentClickEvents, arg.LinkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClickEvent{}
	for rows.Next() {
		var i ClickEvent
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.WorkspaceID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Country,
			&i.City,
			&i.Device,
			&i.Os,
			&i.Browser,
			&i.ReferrerHost,
			&i.Referrer,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topDimensionValues = `-- name: TopDimensionValues :many
SELECT
    value,
    sum(clicks)::bigint AS clicks
FROM click_dimension_daily
WHERE workspace_id = $1
  AND dimension = $2
  AND day >= $3
  AND day <= $4
GROUP BY value
ORDER BY clicks DESC
LIMIT $5
`

type TopDimensionValuesParams struct {
	WorkspaceID uuid.UUID
	Dimension   string
	FromDay     time.Time
	ToDay       time.Time
	RowLimit    int32
}

type TopDimensionValuesRow struct {
	Value  string
	Clicks int64
}

func (q *Queries) TopDimensionValues(ctx context.Context, arg TopDimensionValuesParams) ([]TopDimensionValuesRow, error) {
	rows, err := q.db.Query(ctx, topDimensionValues,
		arg.WorkspaceID,
		arg.Dimension,
		arg.FromDay,
		arg.ToDay,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopDimensionValuesRow{}
	for rows.Next() {
		var i TopDimensionValuesRow
		if err := rows.Scan(&i.Value, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topLinks = `-- name: TopLinks :many
SELECT
    links.id,
    links.slug,
    links.title,
    links.destination_url,
    domains.hostname,
    sum(click_hourly.clicks)::bigint AS clicks
FROM click_hourly
JOIN links   ON links.id = click_hourly.link_id
JOIN domains ON domains.id = links.domain_id
WHERE click_hourly.workspace_id = $1
  AND click_hourly.bucket >= $2
  AND click_hourly.bucket < $3
GROUP BY links.id, links.slug, links.title, links.destination_url, domains.hostname
ORDER BY clicks DESC
LIMIT $4
`

type TopLinksParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
	RowLimit    int32
}

type TopLinksRow struct {
	ID             uuid.UUID
	Slug           string
	Title          *string
	DestinationUrl string
	Hostname       string
	Clicks         int64
}

func (q *Queries) TopLinks(ctx context.Context, arg TopLinksParams) ([]TopLinksRow, error) {
	rows, err := q.db.Query(ctx, topLinks,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopLinksRow{}
	for rows.Next() {
		var i TopLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.DestinationUrl,
			&i.Hostname,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uniqueVisitorsInRange = `-- name: UniqueVisitorsInRange :one
SELECT count(DISTINCT value)::bigint
FROM click_dimension_daily
WHERE workspace_id = $1
  AND dimension = 'visitor'
  AND day >= $2
  AND day <= $3
`

type UniqueVisitorsInRangeParams struct {
	WorkspaceID uuid.UUID
	FromDay     time.Time
	ToDay       time.Time
}

func (q *Queries) UniqueVisitorsInRange(ctx context.Context, arg UniqueVisitorsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, uniqueVisitorsInRange, arg.WorkspaceID, arg.FromDay, arg.ToDay)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertClickDimensionDaily = `-- name: UpsertClickDimensionDaily :exec
INSERT INTO click_dimension_daily (workspace_id, day, dimension, value, clicks)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, day, dimension, value)
DO UPDATE SET clicks = click_dimension_daily.clicks + EXCLUDED.clicks
`

type UpsertClickDimensionDailyParams struct {
	WorkspaceID uuid.UUID
	Day         time.Time
	Dimension   string
	Value       string
	Clicks      int64
}

func (q *Queries) UpsertClickDimensionDaily(ctx context.Context, arg UpsertClickDimensionDailyParams) error {
	_, err := q.db.Exec(ctx, upsertClickDimensionDaily,
		arg.WorkspaceID,
		arg.Day,
		arg.Dimension,
		arg.Value,
		arg.Clicks,
	)
	return err
}

const upsertClickHourly = `-- name: UpsertClickHourly :exec

INSERT INTO click_hourly (workspace_id, link_id, bucket, clicks)
VALUES ($1, $2, $3, $4)
ON CONFLICT (link_id, bucket)
DO UPDATE SET clicks = click_hourly.clicks + EXCLUDED.clicks
`

type UpsertClickHourlyParams struct {
	WorkspaceID uuid.UUID
	LinkID      uuid.UUID
	Bucket      time.Time
	Clicks      int64
}

// Rollup maintenance, called by the analytics worker per drained batch.
func (q *Queries) UpsertClickHourly(ctx context.Context, arg UpsertClickHourlyParams) error {
	_, err := q.db.Exec(ctx, upsertClickHourly,
		arg.WorkspaceID,
		arg.LinkID,
		arg.Bucket,
		arg.Clicks,
	)
	return err
}

const workspaceClickTotals = `-- name: WorkspaceClickTotals :one

SELECT
    coalesce(sum(clicks), 0)::bigint AS total_clicks,
    coalesce(sum(clicks) FILTER (WHERE bucket >= date_trunc('day', now())), 0)::bigint AS clicks_today
FROM click_hourly
WHERE workspace_id = $1
`

type WorkspaceClickTotalsRow struct {
	TotalClicks int64
	ClicksToday int64
}

// Reporting. Every query below reads a rollup table, never click_events.
func (q *Queries) WorkspaceClickTotals(ctx context.Context, workspaceID uuid.UUID) (WorkspaceClickTotalsRow, error) {
	row := q.db.QueryRow(ctx, workspaceClickTotals, workspaceID)
	var i WorkspaceClickTotalsRow
	err := row.Scan(&i.TotalClicks, &i.ClicksToday)
	return i, err
}
