// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clicksOverTime = `-- name: ClicksOverTime :many
SELECT
    date_trunc($1::text, bucket)::timestamptz AS period,
    sum(clicks)::bigint AS clicks
FROM click_hourly
WHERE workspace_id = $2
  AND bucket >= $3
  AND bucket < $4
GROUP BY period
ORDER BY period ASC
`

type ClicksOverTimeParams struct {
	Granularity string
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
}

type ClicksOverTimeRow struct {
	Period time.Time
	Clicks int64
}

func (q *Queries) ClicksOverTime(ctx context.Context, arg ClicksOverTimeParams) ([]ClicksOverTimeRow, error) {
	rows, err := q.db.Query(ctx, clicksOverTime,
		arg.Granularity,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClicksOverTimeRow{}
	for rows.Next() {
		var i ClicksOverTimeRow
		if err := rows.Scan(&i.Period, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clicksOverTimeForLink = `-- name: ClicksOverTimeForLink :many
SELECT
    date_trunc($1::text, bucket)::timestamptz AS period,
    sum(clicks)::bigint AS clicks
FROM click_hourly
WHERE link_id = $2
  AND bucket >= $3
  AND bucket < $4
GROUP BY period
ORDER BY period ASC
`

type ClicksOverTimeForLinkParams struct {
	Granularity string
	LinkID      uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
}

type ClicksOverTimeForLinkRow struct {
	Period time.Time
	Clicks int64
}

func (q *Queries) ClicksOverTimeForLink(ctx context.Context, arg ClicksOverTimeForLinkParams) ([]ClicksOverTimeForLinkRow, error) {
	rows, err := q.db.Query(ctx, clicksOverTimeForLink,
		arg.Granularity,
		arg.LinkID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClicksOverTimeForLinkRow{}
	for rows.Next() {
		var i ClicksOverTimeForLinkRow
		if err := rows.Scan(&i.Period, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteClickEventsBefore = `-- name: DeleteClickEventsBefore :execrows
DELETE FROM click_events WHERE clicked_at < $1
`

// Retention: raw events age out, rollups are kept indefinitely because they
// are tiny. Called by the worker's periodic maintenance pass.
func (q *Queries) DeleteClickEventsBefore(ctx context.Context, clickedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClickEventsBefore, clickedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkClickTotals = `-- name: LinkClickTotals :one
SELECT
    coalesce(sum(clicks), 0)::bigint AS total_clicks,
    coalesce(sum(clicks) FILTER (WHERE bucket >= date_trunc('day', now())), 0)::bigint AS clicks_today
FROM click_hourly
WHERE link_id = $1
`

type LinkClickTotalsRow struct {
	TotalClicks int64
	ClicksToday int64
}

func (q *Queries) LinkClickTotals(ctx context.Context, linkID uuid.UUID) (LinkClickTotalsRow, error) {
	row := q.db.QueryRow(ctx, linkClickTotals, linkID)
	var i LinkClickTotalsRow
	err := row.Scan(&i.TotalClicks, &i.ClicksToday)
	return i, err
}

const recentClickEvents = `-- name: RecentClickEvents :many
SELECT id, link_id, workspace_id, clicked_at, ip_hash, country, city, device, os, browser, referrer_host, referrer, utm_source, utm_medium, utm_campaign FROM click_events
WHERE link_id = $1
ORDER BY clicked_at DESC
LIMIT $2
`

type RecentClickEventsParams struct {
	LinkID uuid.UUID
	Limit  int32
}

func (q *Queries) RecentClickEvents(ctx context.Context, arg RecentClickEventsParams) ([]ClickEvent, error) {
	rows, err := q.db.Query(ctx, recentClickEvents, arg.LinkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClickEvent{}
	for rows.Next() {
		var i ClickEvent
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.WorkspaceID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Country,
			&i.City,
			&i.Device,
			&i.Os,
			&i.Browser,
			&i.ReferrerHost,
			&i.Referrer,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topDimensionValues = `-- name: TopDimensionValues :many
SELECT
    value,
    sum(clicks)::bigint AS clicks
FROM click_dimension_daily
WHERE workspace_id = $1
  AND dimension = $2
  AND day >= $3
  AND day <= $4
GROUP BY value
ORDER BY clicks DESC
LIMIT $5
`

type TopDimensionValuesParams struct {
	WorkspaceID uuid.UUID
	Dimension   string
	FromDay     time.Time
	ToDay       time.Time
	RowLimit    int32
}

type TopDimensionValuesRow struct {
	Value  string
	Clicks int64
}

func (q *Queries) TopDimensionValues(ctx context.Context, arg TopDimensionValuesParams) ([]TopDimensionValuesRow, error) {
	rows, err := q.db.Query(ctx, topDimensionValues,
		arg.WorkspaceID,
		arg.Dimension,
		arg.FromDay,
		arg.ToDay,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopDimensionValuesRow{}
	for rows.Next() {
		var i TopDimensionValuesRow
		if err := rows.Scan(&i.Value, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topLinks = `-- name: TopLinks :many
SELECT
    links.id,
    links.slug,
    links.title,
    links.destination_url,
    domains.hostname,
    sum(click_hourly.clicks)::bigint AS clicks
FROM click_hourly
JOIN links   ON links.id = click_hourly.link_id
JOIN domains ON domains.id = links.domain_id
WHERE click_hourly.workspace_id = $1
  AND click_hourly.bucket >= $2
  AND click_hourly.bucket < $3
GROUP BY links.id, links.slug, links.title, links.destination_url, domains.hostname
ORDER BY clicks DESC
LIMIT $4
`

type TopLinksParams struct {
	WorkspaceID uuid.UUID
	FromTime    time.Time
	ToTime      time.Time
	RowLimit    int32
}

type TopLinksRow struct {
	ID             uuid.UUID
	Slug           string
	Title          *string
	DestinationUrl string
	Hostname       string
	Clicks         int64
}

func (q *Queries) TopLinks(ctx context.Context, arg TopLinksParams) ([]TopLinksRow, error) {
	rows, err := q.db.Query(ctx, topLinks,
		arg.WorkspaceID,
		arg.FromTime,
		arg.ToTime,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopLinksRow{}
	for rows.Next() {
		var i TopLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.DestinationUrl,
			&i.Hostname,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClickDimensionDaily = `-- name: UpsertClickDimensionDaily :exec
INSERT INTO click_dimension_daily (workspace_id, day, dimension, value, clicks)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, day, dimension, value)
DO UPDATE SET clicks = click_dimension_daily.clicks + EXCLUDED.clicks
`

type UpsertClickDimensionDailyParams struct {
	WorkspaceID uuid.UUID
	Day         time.Time
	Dimension   string
	Value       string
	Clicks      int64
}

func (q *Queries) UpsertClickDimensionDaily(ctx context.Context, arg UpsertClickDimensionDailyParams) error {
	_, err := q.db.Exec(ctx, upsertClickDimensionDaily,
		arg.WorkspaceID,
		arg.Day,
		arg.Dimension,
		arg.Value,
		arg.Clicks,
	)
	return err
}

const upsertClickHourly = `-- name: UpsertClickHourly :exec

INSERT INTO click_hourly (workspace_id, link_id, bucket, clicks)
VALUES ($1, $2, $3, $4)
ON CONFLICT (link_id, bucket)
DO UPDATE SET clicks = click_hourly.clicks + EXCLUDED.clicks
`

type UpsertClickHourlyParams struct {
	WorkspaceID uuid.UUID
	LinkID      uuid.UUID
	Bucket      time.Time
	Clicks      int64
}

// Rollup maintenance, called by the analytics worker per drained batch.
func (q *Queries) UpsertClickHourly(ctx context.Context, arg UpsertClickHourlyParams) error {
	_, err := q.db.Exec(ctx, upsertClickHourly,
		arg.WorkspaceID,
		arg.LinkID,
		arg.Bucket,
		arg.Clicks,
	)
	return err
}

const workspaceClickTotals = `-- name: WorkspaceClickTotals :one

SELECT
    coalesce(sum(clicks), 0)::bigint AS total_clicks,
    coalesce(sum(clicks) FILTER (WHERE bucket >= date_trunc('day', now())), 0)::bigint AS clicks_today
FROM click_hourly
WHERE workspace_id = $1
`

type WorkspaceClickTotalsRow struct {
	TotalClicks int64
	ClicksToday int64
}

// Reporting. Every query below reads a rollup table, never click_events.
func (q *Queries) WorkspaceClickTotals(ctx context.Context, workspaceID uuid.UUID) (WorkspaceClickTotalsRow, error) {
	row := q.db.QueryRow(ctx, workspaceClickTotals, workspaceID)
	var i WorkspaceClickTotalsRow
	err := row.Scan(&i.TotalClicks, &i.ClicksToday)
	return i, err
}
