// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (workspace_id, name, key_prefix, key_hash, scopes, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, name, key_prefix, key_hash, scopes, last_used_at, expires_at, revoked_at, created_by, created_at
`

type CreateAPIKeyParams struct {
	WorkspaceID uuid.UUID
	Name        string
	KeyPrefix   string
	KeyHash     string
	Scopes      []string
	ExpiresAt   *time.Time
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.WorkspaceID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createIdempotencyRecord = `-- name: CreateIdempotencyRecord :one
INSERT INTO idempotency_keys (workspace_id, idempotency_key, request_hash, link_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, idempotency_key, request_hash, link_id, created_at, expires_at
`

type CreateIdempotencyRecordParams struct {
	WorkspaceID    uuid.UUID
	IdempotencyKey string
	RequestHash    string
	LinkID         *uuid.UUID
	ExpiresAt      time.Time
}

func (q *Queries) CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyRecord,
		arg.WorkspaceID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.LinkID,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.LinkID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyRecords = `-- name: DeleteExpiredIdempotencyRecords :execrows
DELETE FROM idempotency_keys WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyRecords(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyRecords)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, workspace_id, name, key_prefix, key_hash, scopes, last_used_at, expires_at, revoked_at, created_by, created_at FROM api_keys WHERE key_prefix = $1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT id, workspace_id, idempotency_key, request_hash, link_id, created_at, expires_at FROM idempotency_keys
WHERE workspace_id = $1 AND idempotency_key = $2 AND expires_at > now()
`

type GetIdempotencyRecordParams struct {
	WorkspaceID    uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord, arg.WorkspaceID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.LinkID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, workspace_id, name, key_prefix, key_hash, scopes, last_used_at, expires_at, revoked_at, created_by, created_at FROM api_keys WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND workspace_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
