// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearDefaultDomain = `-- name: ClearDefaultDomain :exec
UPDATE domains SET is_default = FALSE WHERE workspace_id = $1 AND is_default
`

func (q *Queries) ClearDefaultDomain(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultDomain, workspaceID)
	return err
}

const countActiveDomains = `-- name: CountActiveDomains :one
SELECT count(*) FROM domains WHERE workspace_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveDomains(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDomains, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDomains = `-- name: CountDomains :one
SELECT count(*) FROM domains WHERE workspace_id = $1
`

func (q *Queries) CountDomains(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDomains, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (workspace_id, hostname, verification_token, verification_method, is_default)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url
`

type CreateDomainParams struct {
	WorkspaceID        uuid.UUID
	Hostname           string
	VerificationToken  string
	VerificationMethod string
	IsDefault          bool
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.WorkspaceID,
		arg.Hostname,
		arg.VerificationToken,
		arg.VerificationMethod,
		arg.IsDefault,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :execrows
DELETE FROM domains WHERE id = $1 AND workspace_id = $2
`

type DeleteDomainParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDomain, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDefaultDomain = `-- name: GetDefaultDomain :one
SELECT id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url FROM domains
WHERE workspace_id = $1 AND is_default AND status = 'active'
`

func (q *Queries) GetDefaultDomain(ctx context.Context, workspaceID uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getDefaultDomain, workspaceID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
SELECT id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url FROM domains WHERE id = $1
`

func (q *Queries) GetDomain(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}

const getDomainByHostname = `-- name: GetDomainByHostname :one
SELECT id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url FROM domains WHERE LOWER(hostname) = LOWER($1::text)
`

func (q *Queries) GetDomainByHostname(ctx context.Context, hostname string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByHostname, hostname)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}

const getDomainByHostnameInWorkspace = `-- name: GetDomainByHostnameInWorkspace :one
SELECT id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url FROM domains
WHERE LOWER(hostname) = LOWER($1::text)
  AND workspace_id = $2
`

type GetDomainByHostnameInWorkspaceParams struct {
	Hostname    string
	WorkspaceID uuid.UUID
}

func (q *Queries) GetDomainByHostnameInWorkspace(ctx context.Context, arg GetDomainByHostnameInWorkspaceParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByHostnameInWorkspace, arg.Hostname, arg.WorkspaceID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}

const getDomainInWorkspace = `-- name: GetDomainInWorkspace :one
SELECT id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url FROM domains WHERE id = $1 AND workspace_id = $2
`

type GetDomainInWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetDomainInWorkspace(ctx context.Context, arg GetDomainInWorkspaceParams) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainInWorkspace, arg.ID, arg.WorkspaceID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}

const listActiveDomains = `-- name: ListActiveDomains :many
SELECT id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url FROM domains WHERE status = 'active' ORDER BY hostname ASC
`

func (q *Queries) ListActiveDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listActiveDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.VerificationMethod,
			&i.VerificationError,
			&i.SslStatus,
			&i.IsDefault,
			&i.VerifiedAt,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RootRedirectUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainHostnamesForWorkspace = `-- name: ListDomainHostnamesForWorkspace :many
SELECT hostname FROM domains WHERE workspace_id = $1
`

func (q *Queries) ListDomainHostnamesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDomainHostnamesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var hostname string
		if err := rows.Scan(&hostname); err != nil {
			return nil, err
		}
		items = append(items, hostname)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url FROM domains WHERE workspace_id = $1 ORDER BY is_default DESC, created_at ASC
`

func (q *Queries) ListDomains(ctx context.Context, workspaceID uuid.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.VerificationMethod,
			&i.VerificationError,
			&i.SslStatus,
			&i.IsDefault,
			&i.VerifiedAt,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RootRedirectUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsPage = `-- name: ListDomainsPage :many
SELECT id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url FROM domains
WHERE workspace_id = $1
ORDER BY is_default DESC, created_at ASC
LIMIT $3 OFFSET $2
`

type ListDomainsPageParams struct {
	WorkspaceID uuid.UUID
	PageOffset  int32
	PageLimit   int32
}

func (q *Queries) ListDomainsPage(ctx context.Context, arg ListDomainsPageParams) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsPage, arg.WorkspaceID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Hostname,
			&i.Status,
			&i.VerificationToken,
			&i.VerificationMethod,
			&i.VerificationError,
			&i.SslStatus,
			&i.IsDefault,
			&i.VerifiedAt,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RootRedirectUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultDomain = `-- name: SetDefaultDomain :one
UPDATE domains SET is_default = TRUE WHERE id = $1 RETURNING id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url
`

func (q *Queries) SetDefaultDomain(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, setDefaultDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}

const updateDomainRootRedirect = `-- name: UpdateDomainRootRedirect :one
UPDATE domains
SET root_redirect_url = $1,
    updated_at = now()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url
`

type UpdateDomainRootRedirectParams struct {
	RootRedirectUrl *string
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
}

func (q *Queries) UpdateDomainRootRedirect(ctx context.Context, arg UpdateDomainRootRedirectParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainRootRedirect, arg.RootRedirectUrl, arg.ID, arg.WorkspaceID)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}

const updateDomainSSLStatus = `-- name: UpdateDomainSSLStatus :exec
UPDATE domains SET ssl_status = $2 WHERE id = $1
`

type UpdateDomainSSLStatusParams struct {
	ID        uuid.UUID
	SslStatus string
}

func (q *Queries) UpdateDomainSSLStatus(ctx context.Context, arg UpdateDomainSSLStatusParams) error {
	_, err := q.db.Exec(ctx, updateDomainSSLStatus, arg.ID, arg.SslStatus)
	return err
}

const updateDomainVerification = `-- name: UpdateDomainVerification :one
UPDATE domains
SET status = $2,
    ssl_status = $3,
    verification_error = $4,
    verified_at = $5,
    last_checked_at = now()
WHERE id = $1
RETURNING id, workspace_id, hostname, status, verification_token, verification_method, verification_error, ssl_status, is_default, verified_at, last_checked_at, created_at, updated_at, root_redirect_url
`

type UpdateDomainVerificationParams struct {
	ID                uuid.UUID
	Status            string
	SslStatus         string
	VerificationError *string
	VerifiedAt        *time.Time
}

func (q *Queries) UpdateDomainVerification(ctx context.Context, arg UpdateDomainVerificationParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainVerification,
		arg.ID,
		arg.Status,
		arg.SslStatus,
		arg.VerificationError,
		arg.VerifiedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Hostname,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationMethod,
		&i.VerificationError,
		&i.SslStatus,
		&i.IsDefault,
		&i.VerifiedAt,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RootRedirectUrl,
	)
	return i, err
}
