// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLinksForDomain = `-- name: CountLinksForDomain :one
SELECT count(*) FROM links WHERE domain_id = $1
`

func (q *Queries) CountLinksForDomain(ctx context.Context, domainID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLinksForDomain, domainID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLinksInWorkspace = `-- name: CountLinksInWorkspace :one
SELECT
    count(*) AS total,
    count(*) FILTER (WHERE status = 'active') AS active
FROM links
WHERE workspace_id = $1
`

type CountLinksInWorkspaceRow struct {
	Total  int64
	Active int64
}

func (q *Queries) CountLinksInWorkspace(ctx context.Context, workspaceID uuid.UUID) (CountLinksInWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, countLinksInWorkspace, workspaceID)
	var i CountLinksInWorkspaceRow
	err := row.Scan(&i.Total, &i.Active)
	return i, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    workspace_id, domain_id, slug, destination_url, title, status,
    redirect_type, password_hash, expires_at, max_clicks,
    external_reference, metadata, created_by, created_via
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, workspace_id, domain_id, slug, destination_url, title, status, redirect_type, password_hash, expires_at, max_clicks, click_count, external_reference, metadata, created_by, created_via, created_at, updated_at
`

type CreateLinkParams struct {
	WorkspaceID       uuid.UUID
	DomainID          uuid.UUID
	Slug              string
	DestinationUrl    string
	Title             *string
	Status            string
	RedirectType      int16
	PasswordHash      *string
	ExpiresAt         *time.Time
	MaxClicks         *int64
	ExternalReference *string
	Metadata          []byte
	CreatedBy         *uuid.UUID
	CreatedVia        string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.WorkspaceID,
		arg.DomainID,
		arg.Slug,
		arg.DestinationUrl,
		arg.Title,
		arg.Status,
		arg.RedirectType,
		arg.PasswordHash,
		arg.ExpiresAt,
		arg.MaxClicks,
		arg.ExternalReference,
		arg.Metadata,
		arg.CreatedBy,
		arg.CreatedVia,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.Slug,
		&i.DestinationUrl,
		&i.Title,
		&i.Status,
		&i.RedirectType,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxClicks,
		&i.ClickCount,
		&i.ExternalReference,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, workspace_id, domain_id, slug, destination_url, title, status, redirect_type, password_hash, expires_at, max_clicks, click_count, external_reference, metadata, created_by, created_via, created_at, updated_at FROM links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id uuid.UUID) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.Slug,
		&i.DestinationUrl,
		&i.Title,
		&i.Status,
		&i.RedirectType,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxClicks,
		&i.ClickCount,
		&i.ExternalReference,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByExternalReference = `-- name: GetLinkByExternalReference :one
SELECT
    links.id, links.workspace_id, links.domain_id, links.slug, links.destination_url, links.title, links.status, links.redirect_type, links.password_hash, links.expires_at, links.max_clicks, links.click_count, links.external_reference, links.metadata, links.created_by, links.created_via, links.created_at, links.updated_at,
    domains.hostname
FROM links
JOIN domains ON domains.id = links.domain_id
WHERE links.workspace_id = $1 AND links.external_reference = $2
`

type GetLinkByExternalReferenceParams struct {
	WorkspaceID       uuid.UUID
	ExternalReference *string
}

type GetLinkByExternalReferenceRow struct {
	Link     Link
	Hostname string
}

func (q *Queries) GetLinkByExternalReference(ctx context.Context, arg GetLinkByExternalReferenceParams) (GetLinkByExternalReferenceRow, error) {
	row := q.db.QueryRow(ctx, getLinkByExternalReference, arg.WorkspaceID, arg.ExternalReference)
	var i GetLinkByExternalReferenceRow
	err := row.Scan(
		&i.Link.ID,
		&i.Link.WorkspaceID,
		&i.Link.DomainID,
		&i.Link.Slug,
		&i.Link.DestinationUrl,
		&i.Link.Title,
		&i.Link.Status,
		&i.Link.RedirectType,
		&i.Link.PasswordHash,
		&i.Link.ExpiresAt,
		&i.Link.MaxClicks,
		&i.Link.ClickCount,
		&i.Link.ExternalReference,
		&i.Link.Metadata,
		&i.Link.CreatedBy,
		&i.Link.CreatedVia,
		&i.Link.CreatedAt,
		&i.Link.UpdatedAt,
		&i.Hostname,
	)
	return i, err
}

const getLinkInWorkspace = `-- name: GetLinkInWorkspace :one
SELECT
    links.id, links.workspace_id, links.domain_id, links.slug, links.destination_url, links.title, links.status, links.redirect_type, links.password_hash, links.expires_at, links.max_clicks, links.click_count, links.external_reference, links.metadata, links.created_by, links.created_via, links.created_at, links.updated_at,
    domains.hostname
FROM links
JOIN domains ON domains.id = links.domain_id
WHERE links.id = $1 AND links.workspace_id = $2
`

type GetLinkInWorkspaceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type GetLinkInWorkspaceRow struct {
	Link     Link
	Hostname string
}

func (q *Queries) GetLinkInWorkspace(ctx context.Context, arg GetLinkInWorkspaceParams) (GetLinkInWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getLinkInWorkspace, arg.ID, arg.WorkspaceID)
	var i GetLinkInWorkspaceRow
	err := row.Scan(
		&i.Link.ID,
		&i.Link.WorkspaceID,
		&i.Link.DomainID,
		&i.Link.Slug,
		&i.Link.DestinationUrl,
		&i.Link.Title,
		&i.Link.Status,
		&i.Link.RedirectType,
		&i.Link.PasswordHash,
		&i.Link.ExpiresAt,
		&i.Link.MaxClicks,
		&i.Link.ClickCount,
		&i.Link.ExternalReference,
		&i.Link.Metadata,
		&i.Link.CreatedBy,
		&i.Link.CreatedVia,
		&i.Link.CreatedAt,
		&i.Link.UpdatedAt,
		&i.Hostname,
	)
	return i, err
}

const incrementLinkClickCount = `-- name: IncrementLinkClickCount :exec
UPDATE links SET click_count = click_count + $1::bigint
WHERE id = $2
`

type IncrementLinkClickCountParams struct {
	Delta int64
	ID    uuid.UUID
}

func (q *Queries) IncrementLinkClickCount(ctx context.Context, arg IncrementLinkClickCountParams) error {
	_, err := q.db.Exec(ctx, incrementLinkClickCount, arg.Delta, arg.ID)
	return err
}

const listLinksForDomain = `-- name: ListLinksForDomain :many
SELECT links.slug, domains.hostname
FROM links
JOIN domains ON domains.id = links.domain_id
WHERE links.domain_id = $1
`

type ListLinksForDomainRow struct {
	Slug     string
	Hostname string
}

func (q *Queries) ListLinksForDomain(ctx context.Context, domainID uuid.UUID) ([]ListLinksForDomainRow, error) {
	rows, err := q.db.Query(ctx, listLinksForDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksForDomainRow{}
	for rows.Next() {
		var i ListLinksForDomainRow
		if err := rows.Scan(&i.Slug, &i.Hostname); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentLinks = `-- name: RecentLinks :many
SELECT
    links.id, links.workspace_id, links.domain_id, links.slug, links.destination_url, links.title, links.status, links.redirect_type, links.password_hash, links.expires_at, links.max_clicks, links.click_count, links.external_reference, links.metadata, links.created_by, links.created_via, links.created_at, links.updated_at,
    domains.hostname
FROM links
JOIN domains ON domains.id = links.domain_id
WHERE links.workspace_id = $1
ORDER BY links.created_at DESC
LIMIT $2
`

type RecentLinksParams struct {
	WorkspaceID uuid.UUID
	Limit       int32
}

type RecentLinksRow struct {
	Link     Link
	Hostname string
}

func (q *Queries) RecentLinks(ctx context.Context, arg RecentLinksParams) ([]RecentLinksRow, error) {
	rows, err := q.db.Query(ctx, recentLinks, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentLinksRow{}
	for rows.Next() {
		var i RecentLinksRow
		if err := rows.Scan(
			&i.Link.ID,
			&i.Link.WorkspaceID,
			&i.Link.DomainID,
			&i.Link.Slug,
			&i.Link.DestinationUrl,
			&i.Link.Title,
			&i.Link.Status,
			&i.Link.RedirectType,
			&i.Link.PasswordHash,
			&i.Link.ExpiresAt,
			&i.Link.MaxClicks,
			&i.Link.ClickCount,
			&i.Link.ExternalReference,
			&i.Link.Metadata,
			&i.Link.CreatedBy,
			&i.Link.CreatedVia,
			&i.Link.CreatedAt,
			&i.Link.UpdatedAt,
			&i.Hostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestLinkDeletion = `-- name: RequestLinkDeletion :execrows
WITH requested AS (
    UPDATE links
    SET status = 'archived'
    WHERE links.id = $1 AND links.workspace_id = $2
    RETURNING id, workspace_id
)
INSERT INTO deletion_jobs (resource_type, resource_id, workspace_id, not_before)
SELECT 'link', requested.id, requested.workspace_id, now() + interval '5 minutes' FROM requested
ON CONFLICT (resource_type, resource_id) DO NOTHING
`

type RequestLinkDeletionParams struct {
	LinkID      uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) RequestLinkDeletion(ctx context.Context, arg RequestLinkDeletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestLinkDeletion, arg.LinkID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveLink = `-- name: ResolveLink :one
SELECT
    links.id,
    links.workspace_id,
    links.destination_url,
    links.redirect_type,
    links.status,
    links.expires_at,
    links.max_clicks,
    links.click_count,
    links.password_hash
FROM links
JOIN domains ON domains.id = links.domain_id
WHERE LOWER(domains.hostname) = LOWER($1::text)
  AND links.slug = $2::text
  AND domains.status = 'active'
`

type ResolveLinkParams struct {
	Hostname string
	Slug     string
}

type ResolveLinkRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	DestinationUrl string
	RedirectType   int16
	Status         string
	ExpiresAt      *time.Time
	MaxClicks      *int64
	ClickCount     int64
	PasswordHash   *string
}

// Redirect hot path fallback: only used on a Redis cache miss.
func (q *Queries) ResolveLink(ctx context.Context, arg ResolveLinkParams) (ResolveLinkRow, error) {
	row := q.db.QueryRow(ctx, resolveLink, arg.Hostname, arg.Slug)
	var i ResolveLinkRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DestinationUrl,
		&i.RedirectType,
		&i.Status,
		&i.ExpiresAt,
		&i.MaxClicks,
		&i.ClickCount,
		&i.PasswordHash,
	)
	return i, err
}

const slugExistsOnDomain = `-- name: SlugExistsOnDomain :one
SELECT EXISTS (SELECT 1 FROM links WHERE domain_id = $1 AND slug = $2)
`

type SlugExistsOnDomainParams struct {
	DomainID uuid.UUID
	Slug     string
}

func (q *Queries) SlugExistsOnDomain(ctx context.Context, arg SlugExistsOnDomainParams) (bool, error) {
	row := q.db.QueryRow(ctx, slugExistsOnDomain, arg.DomainID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET destination_url = coalesce($1, destination_url),
    title           = CASE WHEN $2::bool THEN $3 ELSE title END,
    status          = coalesce($4, status),
    redirect_type   = coalesce($5, redirect_type),
    expires_at      = CASE WHEN $6::bool THEN $7 ELSE expires_at END,
    max_clicks      = CASE WHEN $8::bool THEN $9 ELSE max_clicks END,
    password_hash   = CASE WHEN $10::bool THEN $11 ELSE password_hash END,
    metadata        = CASE WHEN $12::bool THEN $13 ELSE metadata END,
    slug            = coalesce($14, slug),
    domain_id       = coalesce($15, domain_id)
WHERE id = $16 AND workspace_id = $17
RETURNING id, workspace_id, domain_id, slug, destination_url, title, status, redirect_type, password_hash, expires_at, max_clicks, click_count, external_reference, metadata, created_by, created_via, created_at, updated_at
`

type UpdateLinkParams struct {
	DestinationUrl *string
	SetTitle       bool
	Title          *string
	Status         *string
	RedirectType   *int16
	SetExpiresAt   bool
	ExpiresAt      *time.Time
	SetMaxClicks   bool
	MaxClicks      *int64
	SetPassword    bool
	PasswordHash   *string
	SetMetadata    bool
	Metadata       []byte
	Slug           *string
	DomainID       *uuid.UUID
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.DestinationUrl,
		arg.SetTitle,
		arg.Title,
		arg.Status,
		arg.RedirectType,
		arg.SetExpiresAt,
		arg.ExpiresAt,
		arg.SetMaxClicks,
		arg.MaxClicks,
		arg.SetPassword,
		arg.PasswordHash,
		arg.SetMetadata,
		arg.Metadata,
		arg.Slug,
		arg.DomainID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DomainID,
		&i.Slug,
		&i.DestinationUrl,
		&i.Title,
		&i.Status,
		&i.RedirectType,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxClicks,
		&i.ClickCount,
		&i.ExternalReference,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
