// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	KeyPrefix   string
	KeyHash     string
	Scopes      []string
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	RevokedAt   *time.Time
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

type AppSetting struct {
	Key       string
	Value     []byte
	UpdatedAt time.Time
}

type AuditLog struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	EntityType  string
	EntityID    *uuid.UUID
	EntityLabel *string
	Details     []byte
	CreatedAt   time.Time
}

type ClickDimensionDaily struct {
	WorkspaceID uuid.UUID
	Day         time.Time
	Dimension   string
	Value       string
	Clicks      int64
}

type ClickEvent struct {
	ID           int64
	LinkID       uuid.UUID
	WorkspaceID  uuid.UUID
	ClickedAt    time.Time
	IpHash       *string
	Country      *string
	City         *string
	Device       *string
	Os           *string
	Browser      *string
	ReferrerHost *string
	Referrer     *string
	UtmSource    *string
	UtmMedium    *string
	UtmCampaign  *string
}

type ClickHourly struct {
	WorkspaceID uuid.UUID
	LinkID      uuid.UUID
	Bucket      time.Time
	Clicks      int64
}

type Domain struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	Hostname           string
	Status             string
	VerificationToken  string
	VerificationMethod string
	VerificationError  *string
	SslStatus          string
	IsDefault          bool
	VerifiedAt         *time.Time
	LastCheckedAt      *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type IdempotencyKey struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	IdempotencyKey string
	RequestHash    string
	LinkID         *uuid.UUID
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type Link struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	DomainID          uuid.UUID
	Slug              string
	DestinationUrl    string
	Title             *string
	Status            string
	RedirectType      int16
	PasswordHash      *string
	ExpiresAt         *time.Time
	MaxClicks         *int64
	ClickCount        int64
	ExternalReference *string
	Metadata          []byte
	CreatedBy         *uuid.UUID
	CreatedVia        string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	UserAgent  *string
	IpHash     *string
	ExpiresAt  time.Time
	LastSeenAt time.Time
	CreatedAt  time.Time
}

type SystemBrandingAsset struct {
	Kind        string
	ContentType string
	Data        []byte
	UpdatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Language     string
	Timezone     string
}

type UserTwoFactor struct {
	UserID             uuid.UUID
	SecretCiphertext   []byte
	RecoveryCodeHashes []string
	Enabled            bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Workspace struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	OwnerUserID uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WorkspaceInvitation struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TokenHash   string
	Role        string
	CreatedBy   *uuid.UUID
	ExpiresAt   time.Time
	AcceptedAt  *time.Time
	CreatedAt   time.Time
	RevokedAt   *time.Time
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
