// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	ClearDefaultDomain(ctx context.Context, workspaceID uuid.UUID) error
	ClicksByHourOfDay(ctx context.Context, arg ClicksByHourOfDayParams) ([]ClicksByHourOfDayRow, error)
	ClicksByWeekday(ctx context.Context, arg ClicksByWeekdayParams) ([]ClicksByWeekdayRow, error)
	ClicksInRange(ctx context.Context, arg ClicksInRangeParams) (int64, error)
	ClicksOverTime(ctx context.Context, arg ClicksOverTimeParams) ([]ClicksOverTimeRow, error)
	ClicksOverTimeForLink(ctx context.Context, arg ClicksOverTimeForLinkParams) ([]ClicksOverTimeForLinkRow, error)
	CountActiveDomains(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CountDomainIssues(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CountDomains(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CountExpiringAPIKeys(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CountExpiringLinks(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CountLinksForDomain(ctx context.Context, domainID uuid.UUID) (int64, error)
	CountLinksInWorkspace(ctx context.Context, workspaceID uuid.UUID) (CountLinksInWorkspaceRow, error)
	CountUsers(ctx context.Context) (int64, error)
	CountWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	CountWorkspacesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error)
	CreateIdempotencyRecord(ctx context.Context, arg CreateIdempotencyRecordParams) (IdempotencyKey, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	// Retention: raw events age out, rollups are kept indefinitely because they
	// are tiny. Called by the worker's periodic maintenance pass.
	DeleteClickEventsBefore(ctx context.Context, clickedAt time.Time) (int64, error)
	DeleteDomain(ctx context.Context, arg DeleteDomainParams) (int64, error)
	DeleteExpiredIdempotencyRecords(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	// Visitor hashes have the same retention window as raw click events. Other
	// aggregate dimensions remain tiny and are retained indefinitely.
	DeleteVisitorDimensionsBefore(ctx context.Context, day time.Time) (int64, error)
	FilteredClicksByHourOfDay(ctx context.Context, arg FilteredClicksByHourOfDayParams) ([]FilteredClicksByHourOfDayRow, error)
	FilteredClicksByWeekday(ctx context.Context, arg FilteredClicksByWeekdayParams) ([]FilteredClicksByWeekdayRow, error)
	FilteredClicksInRange(ctx context.Context, arg FilteredClicksInRangeParams) (int64, error)
	FilteredClicksOverTime(ctx context.Context, arg FilteredClicksOverTimeParams) ([]FilteredClicksOverTimeRow, error)
	FilteredTopLinks(ctx context.Context, arg FilteredTopLinksParams) ([]FilteredTopLinksRow, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetDefaultDomain(ctx context.Context, workspaceID uuid.UUID) (Domain, error)
	GetDomain(ctx context.Context, id uuid.UUID) (Domain, error)
	GetDomainByHostname(ctx context.Context, hostname string) (Domain, error)
	GetDomainByHostnameInWorkspace(ctx context.Context, arg GetDomainByHostnameInWorkspaceParams) (Domain, error)
	GetDomainInWorkspace(ctx context.Context, arg GetDomainInWorkspaceParams) (Domain, error)
	GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyKey, error)
	GetLink(ctx context.Context, id uuid.UUID) (Link, error)
	GetLinkByExternalReference(ctx context.Context, arg GetLinkByExternalReferenceParams) (GetLinkByExternalReferenceRow, error)
	GetLinkInWorkspace(ctx context.Context, arg GetLinkInWorkspaceParams) (GetLinkInWorkspaceRow, error)
	GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error)
	GetSetting(ctx context.Context, key string) (AppSetting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	IncrementLinkClickCount(ctx context.Context, arg IncrementLinkClickCountParams) error
	LinkClickTotals(ctx context.Context, linkID uuid.UUID) (LinkClickTotalsRow, error)
	ListAPIKeys(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error)
	ListActiveDomains(ctx context.Context) ([]Domain, error)
	ListDomainHostnamesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]string, error)
	ListDomains(ctx context.Context, workspaceID uuid.UUID) ([]Domain, error)
	ListDomainsPage(ctx context.Context, arg ListDomainsPageParams) ([]Domain, error)
	ListLinksForDomain(ctx context.Context, domainID uuid.UUID) ([]ListLinksForDomainRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWorkspaceMembers(ctx context.Context, arg ListWorkspaceMembersParams) ([]ListWorkspaceMembersRow, error)
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error)
	ListWorkspacesForUserPage(ctx context.Context, arg ListWorkspacesForUserPageParams) ([]ListWorkspacesForUserPageRow, error)
	RecentClickEvents(ctx context.Context, arg RecentClickEventsParams) ([]ClickEvent, error)
	RecentLinks(ctx context.Context, arg RecentLinksParams) ([]RecentLinksRow, error)
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (int64, error)
	RequestLinkDeletion(ctx context.Context, arg RequestLinkDeletionParams) (int64, error)
	RequestWorkspaceDeletion(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// Redirect hot path fallback: only used on a Redis cache miss.
	ResolveLink(ctx context.Context, arg ResolveLinkParams) (ResolveLinkRow, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	SetDefaultDomain(ctx context.Context, id uuid.UUID) (Domain, error)
	SetSetting(ctx context.Context, arg SetSettingParams) (AppSetting, error)
	SlugExistsOnDomain(ctx context.Context, arg SlugExistsOnDomainParams) (bool, error)
	TopDimensionValues(ctx context.Context, arg TopDimensionValuesParams) ([]TopDimensionValuesRow, error)
	TopLinks(ctx context.Context, arg TopLinksParams) ([]TopLinksRow, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UniqueVisitorsInRange(ctx context.Context, arg UniqueVisitorsInRangeParams) (int64, error)
	UpdateDomainRootRedirect(ctx context.Context, arg UpdateDomainRootRedirectParams) (Domain, error)
	UpdateDomainSSLStatus(ctx context.Context, arg UpdateDomainSSLStatusParams) error
	UpdateDomainVerification(ctx context.Context, arg UpdateDomainVerificationParams) (Domain, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error)
	UpsertClickDimensionDaily(ctx context.Context, arg UpsertClickDimensionDailyParams) error
	// Rollup maintenance, called by the analytics worker per drained batch.
	UpsertClickHourly(ctx context.Context, arg UpsertClickHourlyParams) error
	// Reporting. Every query below reads a rollup table, never click_events.
	WorkspaceClickTotals(ctx context.Context, workspaceID uuid.UUID) (WorkspaceClickTotalsRow, error)
}

var _ Querier = (*Queries)(nil)
