// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, updated_at FROM app_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const setSetting = `-- name: SetSetting :one
INSERT INTO app_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
RETURNING key, value, updated_at
`

type SetSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, setSetting, arg.Key, arg.Value)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
