// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING workspace_id, user_id, role, created_at, updated_at
`

type AddWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countWorkspaceMembers = `-- name: CountWorkspaceMembers :one
SELECT count(*) FROM workspace_members WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceMembers, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspacesForUser = `-- name: CountWorkspacesForUser :one
SELECT count(*) FROM workspace_members
JOIN workspaces ON workspaces.id = workspace_members.workspace_id
WHERE workspace_members.user_id = $1 AND workspaces.deletion_requested_at IS NULL
`

func (q *Queries) CountWorkspacesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspacesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, slug, owner_user_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, owner_user_id, created_at, updated_at, deletion_requested_at
`

type CreateWorkspaceParams struct {
	Name        string
	Slug        string
	OwnerUserID uuid.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.OwnerUserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, slug, owner_user_id, created_at, updated_at, deletion_requested_at FROM workspaces WHERE id = $1 AND deletion_requested_at IS NULL
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, owner_user_id, created_at, updated_at, deletion_requested_at FROM workspaces WHERE LOWER(slug) = LOWER($1::text)
  AND deletion_requested_at IS NULL
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, user_id, role, created_at, updated_at FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT
    workspace_members.workspace_id,
    workspace_members.user_id,
    workspace_members.role,
    workspace_members.created_at,
    users.name,
    users.email,
    coalesce(user_two_factor.enabled, false)::boolean AS two_factor_enabled
FROM workspace_members
JOIN users ON users.id = workspace_members.user_id
LEFT JOIN user_two_factor ON user_two_factor.user_id = users.id
WHERE workspace_members.workspace_id = $1
ORDER BY
    CASE workspace_members.role
        WHEN 'owner'  THEN 0
        WHEN 'admin'  THEN 1
        ELSE 2
    END,
    users.name ASC
LIMIT $3 OFFSET $2
`

type ListWorkspaceMembersParams struct {
	WorkspaceID uuid.UUID
	PageOffset  int32
	PageLimit   int32
}

type ListWorkspaceMembersRow struct {
	WorkspaceID      uuid.UUID
	UserID           uuid.UUID
	Role             string
	CreatedAt        time.Time
	Name             string
	Email            string
	TwoFactorEnabled bool
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, arg ListWorkspaceMembersParams) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, arg.WorkspaceID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Name,
			&i.Email,
			&i.TwoFactorEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT
    workspaces.id, workspaces.name, workspaces.slug, workspaces.owner_user_id, workspaces.created_at, workspaces.updated_at, workspaces.deletion_requested_at,
    workspace_members.role
FROM workspaces
JOIN workspace_members ON workspace_members.workspace_id = workspaces.id
WHERE workspace_members.user_id = $1
  AND workspaces.deletion_requested_at IS NULL
ORDER BY workspaces.created_at ASC
`

type ListWorkspacesForUserRow struct {
	Workspace Workspace
	Role      string
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.Name,
			&i.Workspace.Slug,
			&i.Workspace.OwnerUserID,
			&i.Workspace.CreatedAt,
			&i.Workspace.UpdatedAt,
			&i.Workspace.DeletionRequestedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUserPage = `-- name: ListWorkspacesForUserPage :many
SELECT
    workspaces.id, workspaces.name, workspaces.slug, workspaces.owner_user_id, workspaces.created_at, workspaces.updated_at, workspaces.deletion_requested_at,
    workspace_members.role
FROM workspaces
JOIN workspace_members ON workspace_members.workspace_id = workspaces.id
WHERE workspace_members.user_id = $1
  AND workspaces.deletion_requested_at IS NULL
  AND ($2::text = '' OR workspaces.name ILIKE '%' || $2::text || '%')
  AND (
    NOT $3::boolean
    OR (workspaces.created_at, workspaces.id) > ($4::timestamptz, $5::uuid)
  )
ORDER BY workspaces.created_at ASC, workspaces.id ASC
LIMIT $6
`

type ListWorkspacesForUserPageParams struct {
	UserID          uuid.UUID
	Search          string
	HasCursor       bool
	CursorCreatedAt time.Time
	CursorID        uuid.UUID
	PageLimit       int32
}

type ListWorkspacesForUserPageRow struct {
	Workspace Workspace
	Role      string
}

func (q *Queries) ListWorkspacesForUserPage(ctx context.Context, arg ListWorkspacesForUserPageParams) ([]ListWorkspacesForUserPageRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUserPage,
		arg.UserID,
		arg.Search,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserPageRow{}
	for rows.Next() {
		var i ListWorkspacesForUserPageRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.Name,
			&i.Workspace.Slug,
			&i.Workspace.OwnerUserID,
			&i.Workspace.CreatedAt,
			&i.Workspace.UpdatedAt,
			&i.Workspace.DeletionRequestedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :execrows
DELETE FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestWorkspaceDeletion = `-- name: RequestWorkspaceDeletion :execrows
WITH requested AS (
    UPDATE workspaces
    SET deletion_requested_at = now()
    WHERE workspaces.id = $1 AND deletion_requested_at IS NULL
    RETURNING id
)
INSERT INTO deletion_jobs (resource_type, resource_id, workspace_id, not_before)
SELECT 'workspace', requested.id, requested.id, now() + interval '5 minutes' FROM requested
ON CONFLICT (resource_type, resource_id) DO NOTHING
`

func (q *Queries) RequestWorkspaceDeletion(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requestWorkspaceDeletion, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET name = $2 WHERE id = $1 AND deletion_requested_at IS NULL RETURNING id, name, slug, owner_user_id, created_at, updated_at, deletion_requested_at
`

type UpdateWorkspaceParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :one
UPDATE workspace_members
SET role = $3
WHERE workspace_id = $1 AND user_id = $2
RETURNING workspace_id, user_id, role, created_at, updated_at
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
